### ISSUE TITLE
missing template information

### ISSUE THREAD

**Issue by heneault** [CastXML/CastXML#11]
I would like to know how I can get the template name for operators and methods with castxml ? For instance, if we have the following code:

    class ClassA {
     public:
      template < class T > void foo( const T & ) {  }
      template < class T > ClassA & operator=( const T & ) { return * this; }
    };

    void test()
    {
      ClassA a;
      a = 5;
      a.foo("hello");
    }

The xml entry for the operator= and function foo are:

    <Method id="_9" name="foo" returns="_15" context="_5" access="public" location="f1:3" file="f1" line="3" inline="1" attributes="__thiscall__">

and  

    <OperatorMethod id="_10" name="=" returns="_18" context="_5" access="public" location="f1:4" file="f1" line="4" inline="1" attributes="__thiscall__">

This doesn’t expose the template instantiation. Of course, in that particular example, the template is used as the first parameter so I could discover the type this way but it is not portable.

Gccxml was providing a demangled field with that information. For instance:

    <Method id="_10" name="foo" returns="_12" context="_4" access="public" mangled="_ZN6ClassA3fooIA6_cEEvRKT_" demangled="void ClassA::foo&lt;char [6]&gt;(char const (&amp;) [6])" location="f0:3" file="f0" line="3" inline="1">

    <OperatorMethod id="_11" name="=" returns="_13" context="_4" access="public" mangled="_ZN6ClassAaSIiEERS_RKT_" demangled="ClassA&amp; ClassA::operator=&lt;int&gt;(int const&amp;)" location="f0:4" file="f0" line="4" inline="1">

So how can I find the same information ?

Thank you

**Comment by bradking** [comment]
The `mangled` attribute was always provided by gccxml.  I've added the `mangled` attribute to CastXML in commit 0a10370aedd3cc08ebe2a8c0909406859058e146.  It is only on function and variable declarations, not on everything like gccxml did.  Clang does not implement mangling for anything else because nothing else can be a link-time symbol.  Furthermore, when simulating MS compilers the MS-style mangling is now used.

**Comment by bradking** [comment]
The `demangled` attribute was added by gccxml/gccxml@9bce3d53c8fe0c6c49c5c1b909f4b721b60e0775 for human reference but was not intended to provide template instantiation arguments in a structured way.  It just so happened that the string in this attribute could be abused in many cases to extract template argument information (but not in general AFAIK).

The `demangled` attribute happened to be something that gccxml could provide because GCC's source came with a demangler.  Clang provides no demangler in its source and provides no API to print declarations the same way they would appear after demangling.  Therefore CastXML cannot easily provide the `demangled` attribute.  Still, external tools that want to try to extract template information like this could use `abi::__cxa_demangle` and/or `UnDecorateSymbolName` themselves to get it from the `mangled` attribute.
