### ISSUE TITLE
Functions and extern qualifier

### ISSUE THREAD

**Issue by iMichka** [CastXML/CastXML#14]
Hi.
Here is a small problem I encounter with pygccxml.

The following function produced an "extern" qualifier (extern="1") with gccxml:
https://github.com/gccxml/pygccxml/blob/develop/unittests/data/declarations_calldef.hpp#L15

This is no more the case with castxml. Pygccxml's code is working correctly, it's just one of the tests was expecting the extend qualifier. I could just adapt the test, or is this something that would need to be changed in castxml ?

**Comment by bradking** [comment]
I think the test should be adapted.  CastXML adds the `extern="1"` when Clang reports the `SC_Extern` storage class (as against others like `SC_Static` or `SC_None`) for a declaration.  IIUC this happens when an explicit `extern` appears in the source code.  I think gccxml printed this all the time because GCC did not distinguish between explicit and defaulted linkage specifiers.

**Comment by iMichka** [comment]
Thanks for the precisions. I adapted the test.
