### ISSUE TITLE
preprocessor defines

### ISSUE THREAD

**Issue by exetoc** [CastXML/CastXML#21]
can preprocessor defines be included in the output?

**Comment by bradking** [comment]
One may run `castxml -E -dD src.cpp` or `castxml -E -dM src.cpp` to see preprocessor definitions, but they don't go in the xml output.

Currently the only option for generating xml output is `--castxml-gccxml` that is intended to produce output close to that of our predecessor, `gccxml`.  The gccxml output does not include anything about preprocessor definitions.  If we were to start adding information that gccxml did not provide then we would need to introduce a new output option to request such an alternative format.  That is beyond our goals at this stage of the project, but discussion for future directions is still worthwhile.

The generated xml is declarative and unordered.  Preprocessor definitions change while processing a translation unit.  At what point should they be considered?  What kind of definitions are of interest?

**Comment by exetoc** [comment]
Right. Well, the goal is to automate the generation of bindings, and some headers are riddled with preprocessor directives.

**Comment by bradking** [comment]
Please provide a concrete example of what you have in mind.

**Comment by vl409** [comment]
I'd like to also request this feature.
Why do we need it?
For example, I'm trying to create openSSL library binding to some scripting language using FFI.
CastXML is really helpful in getting all types informations and functions declaration.
The problem is that big part of openSSL interface is defined by macros.
The simplest example is defines, tons of them:
# define EVP_PKEY_OP_PARAMGEN            (1<<1)                                 
# define EVP_PKEY_OP_KEYGEN              (1<<2)
....
# define EVP_PKEY_OP_TYPE_SIG    \                                              
        (EVP_PKEY_OP_SIGN | EVP_PKEY_OP_VERIFY | EVP_PKEY_OP_VERIFYRECOVER \    
                | EVP_PKEY_OP_SIGNCTX | EVP_PKEY_OP_VERIFYCTX)  
Many function names are auto-generated.

So, you read documentation that tells you to call function foo(), but it is not in list,
generated from XML.  Or you have to pass some constant to known function...
You have to inspect headers and blame library authors
who use macros. But the reality is such that it is too common to use preprocessor.

I understand that there is not much we can do about it, but some attempt to extract
at least constants would be nice.

**Comment by rprzybyla-invn** [comment]
I'm also using CastXML (through the library pycstruct) to read a header file that defines a C struct for a shared memory interface to hardware. The C struct has several bitfields to save space in the struct, but in order to access those fields one must manually copy the #define statements to the python environment that I am using, or find some other solution.
