### ISSUE TITLE
Skipping methods containing rvalue reference parameters

### ISSUE THREAD

**Issue by reubenjohn** [CastXML/CastXML#242]
Notice the rvalue reference parameter **B&&** of the **MyClass::update** method shown below. It causes the update method to be skipped in the castxml XML output entirely. Simply making it a lvalue reference **B&** causes it to pop up in the output.

```
namespace test {
class A { };
class B { };

template<typename T1>
class MyClass {
...
void update(B&& b) { ... }
};

// Explicit instantiation
template void MyClass<A>::update(B&&);
}
```
The templatization may be unnecessary to reproduce this issue.

**Comment by bradking** [comment]
This is due to code [here](https://github.com/CastXML/CastXML/blob/v0.5.1/src/Output.cxx#L694-L707) that intentionally filters them out.  It's left from a transition period when CastXML was trying to reproduce GCC-XML's output, which didn't support C++11.  We never got around to revising the conditions for CastXML-specific output.

**Comment by bradking** [comment]
I've been meaning to do this for a long time.  Thanks for the ping.

#243 implements this.
