### ISSUE TITLE
Support for `__attribute__((gccxml(#x)))`?

### ISSUE THREAD

**Issue by xoofx** [CastXML/CastXML#25]
Hi there!
I'm a fan of gccxml and I have been using it extensively in the project [SharpDX](https://github.com/sharpdx/SharpDX) to generate .NET wrapper from C++ DirectX headers.

One of my major requirement is the support for `declspec` attributes, that allows to parse SAL annotations in Windows headers...
When using gccxml, I remmember I was able to use such a macro like this:

    #define __declspec(x) __attribute__((gccxml(#x)))

Does CastXML support this scenario? I'm not sure if clang have some support for attached metadata attributes...
Thanks!

**Comment by bradking** [comment]
I've edited the issue subject line to clarify that this is about the `gccxml(...)` attribute rather than `dllexport` markup.  The latter is supported.

Unfortunately CastXML is not able to support the arbitrary `gccxml(...)` attributes.  This is because Clang represents each supported attribute with dedicated source structures, so additional attributes cannot be handled.  One can see this in the Clang source tree where the attributes are declared in the `include/clang/Basic/Attr.td` file.

One might be able to use the `annotate` attribute instead.  It appears to accept a string as an argument.  I have not tried it though.

**Comment by xoofx** [comment]
`annotate` attribute looks exactly what I'm looking for, thanks for pointing this out. I will give it a try

**Comment by bradking** [comment]
Great.  I have some local changes to include the `annotate(...)` attribute in the `attributes=""` XML element attribute just like gccxml did with `gccxml(...)`.  It still needs more testing before I push it out though.

**Comment by bradking** [comment]
I've implemented support for `annotate(...)` in commit e73fba54fd7347b94a6951903eac8479495654f2.

**Comment by xoofx** [comment]
Oh, that's cool, thanks!

**Comment by iMichka** [comment]
I just made a PR to add annotation to function arguments. This was also allowed in gccxml so I guess we can implement it in castxml: https://github.com/CastXML/CastXML/pull/26
