### ISSUE TITLE
Qualified names in default arguments

### ISSUE THREAD

**Issue by praetorian20** [CastXML/CastXML#51]
CastXML currently populates the `default` attribute for a function default argument with the same text as what was in the header it parsed. This causes code generated by pyplusplus to not compile because the names are not correctly qualified when creating the Boost.Python binding. For example, parsing the following

```
namespace ns
{

enum fruit{ apple, orange };
void fun1( fruit arg1 = apple );

struct st1
{
   static const int DEFAULT = 0;
   void fun2( int arg2 = DEFAULT );
};

typedef unsigned long long ull;
void fun3( ull arg3 = (ull)-1 );

}
```
with the command

    castxml  -I. -c -x c++ --castxml-cc-gnu  g++ --castxml-gccxml -o default_args.cpp.xml default_args.hpp

produces the following output for default arguments

```
<Argument name="arg1" type="_11" location="f1:30" file="f1" line="30" default="apple"/>
<Argument name="arg2" type="_29" location="f1:35" file="f1" line="35" default="DEFAULT"/>
<Argument name="arg3" type="_14" location="f1:39" file="f1" line="39" default="(ull)-1"/>
```
Parsing the same header using gccxml produces
```
<Argument name="arg1" type="_161" location="f1:30" file="f1" line="30" default="apple"/>
<Argument name="arg2" type="_146" location="f1:35" file="f1" line="35" default="ns::st1::DEFAULT"/>
<Argument name="arg3" type="_163" location="f1:39" file="f1" line="39" default="-1u"/>
```
`arg1` can be patched rather easily to have a fully qualified name, and pygccxml has the machinery to do that, but the other two are trickier.

Would it be possible to have CastXML put fully qualified names in default arguments? The ideal default values for the code above would be
```
default="ns::apple"
default="ns::st1::DEFAULT"
default="-1ull"
```
If the `enum` is a C++11 scoped enum, then the first one would have to be `default="ns::fruit::apple"` (but as I said earlier, the enum is less important, I can patch that pretty reliably in pygccxml). If literals cannot be transformed to the final type as GCCXML (incorrectly) does, then the last one could be `default=(ns::ull)-1"`.

**Comment by bradking** [comment]
Unfortunately Clang may not make it easy to get this information.  In CastXML's source there is a call to `getInit()` in `ASTVisitor::OutputFunctionHelper` that gets the default expression as a `clang::Expr`.  CastXML is just printing that expression.  However, the expression appears to use `clang::DeclRefExpr` at the leaves which only has raw identifier information about what appeared in the source code.  That contains qualifiers only if the source code did.  I'm not particularly familiar with this part of Clang's representation, but it appears that the lookup of the actual referenced declaration may not be done until a call site needs to use the default argument.

**Comment by praetorian20** [comment]
I posted a [question](http://clang-developers.42468.n3.nabble.com/Qualified-names-in-default-arguments-for-function-parameters-td4050582.html) on the clang mailing list. Maybe someone there will be able to help us out.

**Comment by bradking** [comment]
Actually it turns out that DeclRefExpr does give us the actual declaration underneath.  I have a patch in progress.

**Comment by bradking** [comment]
Fixed partially by commit 85f0c93da63741a2bb268ac6b3f6f900305bbd00.  That takes care of the `ns::st1::DEFAULT` and `ns::fruit::apple` cases because those appear in the default argument expression as `DeclRefExpr`.  Additional work is still needed for the `(ull)-1` and other cast-expression cases because they reference types rather than declarations.

**Comment by bradking** [comment]
The `DeclRefExpr` case was possible to fix because the statement/expression printing API in Clang's AST provides a `PrinterHelper` argument that we can use to hook in and print `DeclRefExpr` with a custom method.

Unfortunately the `(ull)-1` casting case is not possible to fix so easily.  While our `PrinterHelper` hook could recognize `CStyleCastExpr` and `CXXNamedCastExpr` it would not be able to customize the type printing without re-implementing the whole thing.  Clang's `Type` printing API does not have a `PrinterHelper` hook.  Therefore we cannot change the `Type` printing to look up the corresponding declarations and print their fully qualified names.

For reference, Clang's expression printing for casts is implemented in `StmtPrinter::VisitCStyleCastExpr` and `StmtPrinter::VisitCXXNamedCastExpr`.  One can see their use of `Node->getTypeAsWritten().print(OS, Policy)` for printing the casted-to type exactly as it was written in the source.

Fixing this will likely require modification to Clang upstream to add hooks or customization options to its `TypePrinter`.  It is not clear that a hook would be easy to define because `TypePrinter` has internal state and APIs that may need to be exposed for such a hook to do something useful, especially with nested types.

**Comment by bradking** [comment]
While we cannot customize the printing of a `Type` we can control which type is printed.  A middle ground solution is implemented in commit 86c6385eee64dcd3107a59b443e5a89f854d9da9.  We now print the canonical type in cast expressions instead of the type as written.  This unwraps typedefs and such but will print a fully qualified name or a fundamental type name so that tools can know the actual type which is more useful than an unqualified typedef.

I also followed up with commit b3fbd7aaf6ab06c01231566efa46ac51817a4409 to activate all this for variable `init="..."` expressions too.

**Comment by bradking** [comment]
@iMichka please take a look at the changes discussed here to see if it affects pygccxml or its tests.

**Comment by iMichka** [comment]
@bradking thanks for notifying me. I was following the discussion with one eye.

The following pull request is currently trying to address some of these problems: https://github.com/gccxml/pygccxml/pull/43

When I updated to CastXML, I saw that the output was slightly different; but as the default values were the same as in the source code, I said myself that this was probably a good thing. I did not realize that py++ was relying on it to be written as described here.

@praetorian20 the https://github.com/gccxml/pygccxml/pull/43 pull request probably will need to be adapted a little bit more.

Maybe we should bump the revision number to 1.137 in the xml file, so that we can discriminate between newer and older castxml versions. @praetorian20 we would only have tests for the new behaviour; no need to test the old one which was wrong.

**Comment by praetorian20** [comment]
@bradking Thank you so much for fixing this problem. I think your solution for unwrapping types in a cast expression should work just fine. I agree with @iMichka that it's probably a good idea to bump a version number somewhere so pygccxml can detect CastXML versions that produce the correct output. I've submitted a couple of different PRs over the past week to patch some of the easier use cases, and we might need to make sure that code doesn't interfere with the new functionality.

@iMichka I'll update my CastXML and re-test this weekend.

**Comment by bradking** [comment]
I've updated the `cvs_revision` number in commit 5a90589770fd53510981f943844cb488eb58bd91.

**Comment by praetorian20** [comment]
Found a bug with `enum` qualification. Given this code

```
namespace fx{
    enum{ unnamed = 0 };
    void fix_unnamed( int x=unnamed );
}
```
latest CastXML is generating
```
  <Enumeration id="_1162" name="" ...>
    <EnumValue name="unnamed" init="0"/>
  </Enumeration>
  <Function id="_1163" name="fix_unnamed" ...>
    <Argument name="x" ... default="fx::::unnamed"/>
  </Function>
```
The default value is being generated as `fx::::unnamed` because the `enum` doesn't have a name.
