### ISSUE TITLE
--cast-gccxml does not work with c11

### ISSUE THREAD

**Issue by Skarsnik** [CastXML/CastXML#54]
I can't make castxml to work at all on C header. I tried a simple castxml --cast-gccxml -o plop.xml /usr/include/libio.h but it always complain that it does not support c11

**Comment by bradking** [comment]
Meanwhile one can work around this by adding the `-std=c89` flag.

**Comment by bradking** [comment]
Thanks for pointing this out.  The error message was first added to reject unsupported combinations.  Since then a lot of other infrastructure has been developed to support the various C++ language levels.  It turns out that the only thing left to support the various C language levels is to remove the error check and add test cases.

After generalizing the C test infrastructure to support multiple dialects in commit b1d7df8cb06621d6db025c9b9ea3ed4d6f03e6ad, I've enabled support for `c99` and `c11` in commit 2edc188fd48a6a8467610d9d559985c4893c879a.

**Comment by Skarsnik** [comment]
Oh good. Thanks. I am using gccxml to generate perl6 code from C header and I was not able to have a working castxml to replace it when the distrib does not provide it. (and I need c99+ support)
